title: My Title here
owner: Darya Plotnytska
email: d.plotnytska.s@gmail.com
description: ""
baseurl: /poetry
url: https://ryaplots.github.io
language: en
# Build settings
markdown: kramdown
theme: minima

permalink: /:year/:month/:day/:title/

plugins:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor/bundle
excerpt_separator: <!--more-->
